### ISSUE TITLE
Problems building with gcc 4.7.2

### ISSUE THREAD

**Issue by mgangel** [Kingsford-Group/ribomap#1]
After I make with: make riboprof INC="-I/nethome/angelmg/include"

I get the error "bam_parser.cpp:368:9: error: ‘using rd_rec_map_t = class std::mapstd::basic_string<char, fp_record>’ has no member named ‘emplace’"

Is gcc 4.8 minimal requirement?

**Comment by how-wonderful** [comment]
emplace is indeed a c++11 function. But I thought gcc 4.7 already support c++11. You can try compiling it with gcc 4.8. Please also make sure to use seqan version 1.4.1. (http://packages.seqan.de/)

**Comment by rob-p** [comment]
Indeed, `emplace` wasn't added to `libstdc++` until gcc 4.8 see e.g. [here](http://stackoverflow.com/questions/15812276/stdset-has-no-member-emplace).  G++ 4.7 is only _mostly_ C++11 compatible.  I actually am not sure exactly when gcc reached full C++11 compliance, but I don't believe it was until 4.9.x or 5.0.
