### ISSUE TITLE
.base file contains decimals for ribo profile 

### ISSUE THREAD

**Issue by ahorvath** [Kingsford-Group/ribomap#11]
Dear Authors,

Many thanks for the great package. Working with the pipeline,  I wonder why the .base/.codon files contain decimal values for "ribo profile" entry?

Or are they already estimated values instead of the raw read counts for mRNA/ribo-seq?

Thanks for the answer.

Best,
Attila

**Comment by how-wonderful** [comment]
@ahorvath 
Thanks for your interest! Both ribo and mRNA read counts are indeed estimated values, they are stored as `double` in the cpp code (See [here](https://github.com/Kingsford-Group/ribomap/blob/master/src/profile_writer.cpp#L54)).
