### ISSUE TITLE
Building error with gcc 4.8.2

### ISSUE THREAD

**Issue by ghost** [Kingsford-Group/ribomap#3]
I get error:
bam_parser.cpp:302:3: error: ‘BamStream’ is not a member of ‘seqan’

g++ -std=c++11 -O3 -Wno-deprecated-declarations -DSEQAN_HAS_ZLIB=1 -DSEQAN_HAS_BZIP2=1     -c -o read_mapper.o read_mapper.cpp
g++ -std=c++11 -O3 -Wno-deprecated-declarations -DSEQAN_HAS_ZLIB=1 -DSEQAN_HAS_BZIP2=1     -c -o ribomap_profiler.o ribomap_profiler.cpp
g++ -std=c++11 -O3 -Wno-deprecated-declarations -DSEQAN_HAS_ZLIB=1 -DSEQAN_HAS_BZIP2=1     -c -o bam_parser.o bam_parser.cpp
In file included from /apps/RH6U4/seqan/2.1.1/include/seqan/basic.h:101:0,
                 from /apps/RH6U4/seqan/2.1.1/include/seqan/bam_io.h:45,
                 from bam_parser.cpp:36:
bam_parser.cpp: In function ‘bool get_expressed_alignments_from_bam(rd_rec_map_t&, const char*, const ribo_profile&, const string&, int, int, bool, bool)’:
bam_parser.cpp:302:3: error: ‘BamStream’ is not a member of ‘seqan’
   seqan::BamStream bamIn(fn);
   ^
bam_parser.cpp:303:15: error: ‘bamIn’ was not declared in this scope
   if (!isGood(bamIn)){
               ^
bam_parser.cpp:303:20: error: ‘isGood’ was not declared in this scope
   if (!isGood(bamIn)){
                    ^
bam_parser.cpp:308:16: error: ‘bamIn’ was not declared in this scope
   while(!atEnd(bamIn)){
                ^
bam_parser.cpp:308:21: error: ‘atEnd’ was not declared in this scope
   while(!atEnd(bamIn)){
                     ^

**Comment by how-wonderful** [comment]
Seems you are using seqan version 2.1.1, which is different from what Ribomap uses. Could you try seqan [version 1.4.1](http://packages.seqan.de/) instead?

**Comment by ghost** [comment]
Thanks. Using seqan 1.4.1 solved the problem
