### ISSUE TITLE
Stranded RNA-Seq on opposing strand

### ISSUE THREAD

**Issue by nickstiffler** [Kingsford-Group/ribomap#8]
Hi,
Our RNA-Seq protocol results in fragments that align to only the opposite strand of the transcript, but  the riboseq reads align to the forward strand. Your pipeline assumes stranded reads will always align to the forward strand. I have made a change to the library type of salmon in the run_ribomap.sh script, so I am able to process my data, but I thought I should bring this up so additional options could be added to ribomap in future releases to accommodate this. Thanks.

Nick

**Comment by ckingsford** [comment]
Thanks! This is a good point. We'll try to add this in a future release of ribomap.

**Comment by how-wonderful** [comment]
Good point!

**Comment by how-wonderful** [comment]
boo

**Comment by how-wonderful** [comment]
good point again!

**Comment by how-wonderful** [comment]
good point!

**Comment by hadjie01** [comment]
Hello! I am trying to do the same because my RNA-Seq data is on the opposite strand (SR). Could you please let me know what type of modifications I'll need to do to the script?
Thanks a lot!!
