### ISSUE TITLE
riboprof  /lib64/libc.so.6: version `GLIBC_2.14' not found (required by riboprof)

### ISSUE THREAD

**Issue by misik** [Kingsford-Group/ribomap#9]
Hello,

I ran the ribomap with the code: 
ribomap-linux/scripts/run_ribomap.sh  --rnaseq_fq SRR403882.fastq.gz --riboseq_fq SRR403888.fastq.gz --transcript_fa gencode.v25.pc_transcripts.fa --rnaUnstranded true --max_fplen 40

STAR aligner and salmon worked fine but riboprof gave an error:
[2017-03-20 10:46:32.646] [jointLog] [info] iteration = 3100 | max rel diff. = 0.0179488
[2017-03-20 10:46:34.661] [jointLog] [info] iteration = 3200 | max rel diff. = 0.0141226
[2017-03-20 10:46:36.727] [jointLog] [info] iteration = 3300 | max rel diff. = 0.0119682
[2017-03-20 10:46:37.704] [jointLog] [info] iteration = 3349 | max rel diff. = 0.00995365

writing output
[2017-03-20 10:46:37.709] [jointLog] [info] finished optimizer

Freeing memory used by read queue . . .
Joined parsing thread . . . "ribomap-linux/scripts/../alignment/SRR403882_transcript_Aligned.out.bam"
Closed all files . . .
Emptied frag queue. . .
Emptied Alignemnt Group Pool. .
Emptied Alignment Group Queue. . . done
running riboprof...
riboprof: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by riboprof)
riboprof: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by riboprof)
riboprof: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by riboprof)
riboprof: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by riboprof)
riboprof: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by riboprof)
pipeline failed at ribosome profile generation!

How can I solve this problem?

Also, should I run ribomap for each replicate separately or do you recommend combining fastq.gz files for replicates before running ribomap? 

Thank you,
Meltem

**Comment by ckingsford** [comment]
This looks like a version problem with the libraries installed on your system. What OS are you using? Which version?

Carl

**Comment by misik** [comment]
I use this cluster: https://wiki.med.harvard.edu/Orchestra/WebHome

It's Linux based system.

Thank you,
Meltem



Op maandag 20 maart 2017 heeft Carl Kingsford <notifications@github.com>
het volgende geschreven:

> This looks like a version problem with the libraries installed on your
> system. What OS are you using? Which version?
>
> Carl
>
> > On Mar 20, 2017, at 11:12 AM, misik <notifications@github.com

**Comment by how-wonderful** [comment]
Meltem,
You might try recompiling `riboprof` from source. Please use seqAn version 1.4.2 for compilation.

**Comment by how-wonderful** [comment]
Meltem,
In terms of merging replicates or not, it depends on the goal of merging. If you want to get a higher coverage, it makes sense to merge two replicates.
